### ISSUE TITLE
Version on Microsoft Store is not the latest one

### ISSUE THREAD

**Issue by qrospars** [Lukas34/ShutdownTimerClassic#2]
Just wanted to open this issue to be sure that are aware of it :)

**Comment by Lukas34** [comment]
Thanks 👍 but I am aware of that.
The Microsoft Store doesn't let me upload this version so I am currently looking into new stuff that I could implement to update the version 1.0.5.

The reason for this is that I tried out the [Package Flights](https://docs.microsoft.com/en-us/windows/uwp/publish/package-flights) feature in the Store and gave it an early preview of the 1.0.4 version to send to a few friends, just to test it out. When I tried to release the actual 1.0.4 version I deleted the flight package and uploaded the real one to the Store but now it doesn't accept any packages with the version 1.0.4 as there already was a package with the version 1.0.4 in the Store.

So, let me know if you have any suggestions for stuff I could change. I don't really want to create a new version with no changes.

**Comment by Lukas34** [comment]
Alright, the new version v1.1.0 is now also in the Microsoft Store and will be slowly rolled out. ✔

Only a small percentage of people will get updated at first to ensure any unexpected issues are limited to a small group but it will eventually be rolled out to everyone, manually checking for updates will always get you the newest version tho.
